Fix reference-cast compile error
Fixes a compilation error on GCC due to the casting of a const-reference into a non-const-reference type:

```
../../include/hlsl++/dependent.h: In function ‘hlslpp::int1 hlslpp::asint(const float1&)’:
../../include/hlsl++/dependent.h:132:67: error: casting ‘const hlslpp::float1’ to ‘hlslpp::int1&’ does not use ‘hlslpp::int1::int1(const hlslpp::float1&)’ [-Werror=cast-user-defined]
  132 |         hlslpp_inline int1 asint(const float1& v) { return (int1&)v; }
      |                                                                   ^
../../include/hlsl++/dependent.h: In function ‘hlslpp::int2 hlslpp::asint(const float2&)’:
../../include/hlsl++/dependent.h:133:67: error: casting ‘const hlslpp::float2’ to ‘hlslpp::int2&’ does not use ‘hlslpp::int2::int2(const hlslpp::float2&)’ [-Werror=cast-user-defined]
  133 |         hlslpp_inline int2 asint(const float2& v) { return (int2&)v; }
      |                                                                   ^
../../include/hlsl++/dependent.h: In function ‘hlslpp::int3 hlslpp::asint(const float3&)’:
../../include/hlsl++/dependent.h:134:67: error: casting ‘const hlslpp::float3’ to ‘hlslpp::int3&’ does not use ‘hlslpp::int3::int3(const hlslpp::float3&)’ [-Werror=cast-user-defined]
  134 |         hlslpp_inline int3 asint(const float3& v) { return (int3&)v; }
      |                                                                   ^
../../include/hlsl++/dependent.h: In function ‘hlslpp::int4 hlslpp::asint(const float4&)’:
../../include/hlsl++/dependent.h:135:67: error: casting ‘const hlslpp::float4’ to ‘hlslpp::int4&’ does not use ‘hlslpp::int4::int4(const hlslpp::float4&)’ [-Werror=cast-user-defined]
  135 |         hlslpp_inline int4 asint(const float4& v) { return (int4&)v; }
...
```